# RVM
eval "$(rbenv init -)"

# NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# asdf
. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

# Keep shell history for erlang/elixir
export ERL_AFLAGS="-kernel shell_history enabled"

# Set editor to open ruby gems using `bundle open gem`
export EDITOR="vim"

PATH=$PATH:/usr/local/sbin
