# asdf
. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

# Keep shell history for erlang/elixir
export ERL_AFLAGS="-kernel shell_history enabled"

# Set editor to open ruby gems using `bundle open gem`
export EDITOR="vim"

PATH=$PATH:/usr/local/sbin

# AWS cli
export PATH=~/Library/Python/2.7/bin:$PATH
export AWS_DEFAULT_REGION=us-east-1
export AWS_PAGER=""

# Set default locale for VIM
export LC_ALL=en_US.UTF-8

# direnv
eval "$(direnv hook zsh)"

# Mix escripts (mostly for Twirp for now)
export PATH=$PATH:/Users/tegon/.asdf/installs/elixir/1.11.2-otp-23/.mix/escripts

source $HOME/.zlogin-secure

# RVM
eval "$(rbenv init -)"
