#!/bin/bash

echo "Setup configuration files..."

config_files=~/dotfiles/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

echo "Creating src directory..."
mkdir -p ~/src/private

echo "Setting iterm2 preferences folder..."
defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "~/dotfiles/iterm"
defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

echo "Installing dependencies..."
npm install --global pure-prompt

echo "Done :)"
