#!/bin/bash

echo "Setup configuration files..."

config_files=~/dotfiles/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

echo "Done :)"
